### ISSUE TITLE
Support for `default`?

### ISSUE THREAD

**Issue by SamuelMarks** [Clever/json-schema-converter#20]
JSON-Schema supports specifying default values, as does Mongoose.

Can support for this feature be added to json-schema-converter?

(wrote a test to show it failing: https://github.com/SamuelMarks/json-schema-converter)

**Comment by jon49** [comment]
Is the project dead?

**Comment by jon49** [comment]
Since no one responded, I just rewrote it, so my project (built on top of this one) supports `default` among other missing things. https://github.com/jon49/json-schema-to-mongoose

**Comment by SamuelMarks** [comment]
Nice looking project, will be sure to check it out next time I'm working in the Node.JS world =)
